=== zenbones/SmallMind/nutsnbolts/src/main/resources/xsd/org/smallmind/nutsnbolts/smallmind-command-1.0.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" targetNamespace="http://www.smallmind.org/schema/nutsnbolts/command" xmlns="http://www.smallmind.org/schema/nutsnbolts/command" elementFormDefault="qualified">

  <xs:element name="options">
    <xs:complexType>
      <xs:choice minOccurs="1" maxOccurs="unbounded">
        <xs:element ref="option"/>
      </xs:choice>
    </xs:complexType>
  </xs:element>

  <xs:element name="option">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="arguments"/>
        <xs:element ref="options" minOccurs="0"/>
      </xs:sequence>
      <xs:attribute name="name" type="optionName"/>
      <xs:attribute name="flag" type="optionFlag"/>
      <xs:attribute name="required" type="xs:boolean" default="false"/>
    </xs:complexType>
  </xs:element>

  <xs:element name="arguments">
    <xs:complexType>
      <xs:choice>
        <xs:element ref="none"/>
        <xs:element name="single" type="xs:string"/>
        <xs:element name="list" type="xs:string"/>
        <xs:element ref="enumerated"/>
      </xs:choice>
    </xs:complexType>
  </xs:element>

  <xs:element name="none">
    <xs:complexType>
    </xs:complexType>
  </xs:element>

  <xs:element name="enumerated">
    <xs:complexType>
      <xs:sequence minOccurs="1" maxOccurs="unbounded">
        <xs:element name="value" type="xs:string"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>

  <xs:simpleType name="optionName">
    <xs:restriction base="xs:string">
      <xs:pattern value="[A-Za-z][-._A-Za-z0-9]*"/>
    </xs:restriction>
  </xs:simpleType>

  <xs:simpleType name="optionFlag">
    <xs:restriction base="xs:string">
      <xs:pattern value="[A-Za-z]"/>
    </xs:restriction>
  </xs:simpleType>
</xs:schema>

=== zenbones/SmallMind/nutsnbolts/src/test/resources/meta/org/smallmind/nutsnbolts/command/sax/SampleApp.arguments.xml
<?xml version="1.0" encoding="UTF-8"?>
<options xmlns="http://www.smallmind.org/schema/nutsnbolts/command"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://www.smallmind.org/schema/nutsnbolts/command http://www.smallmind.org/schema/nutsnbolts/smallmind-command-1.0.xsd">
  <option name="input" flag="i" required="true">
    <arguments>
      <single>path</single>
    </arguments>
  </option>
  <option name="verbose" flag="v">
    <arguments>
      <none/>
    </arguments>
  </option>
  <option name="files" flag="f">
    <arguments>
      <list>paths</list>
    </arguments>
  </option>
  <option name="level" flag="l">
    <arguments>
      <enumerated>
        <value>low</value>
        <value>medium</value>
        <value>high</value>
      </enumerated>
    </arguments>
  </option>
</options>

=== zenbones/SmallMind/forge/deploy/src/main/resources/meta/org/smallmind/forge/deploy/cli/ApplicationUpdaterCLIArguments.xml
<?xml version="1.0" encoding="UTF-8"?>
<options xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns="http://www.smallmind.org/schema/nutsnbolts/command"
         xsi:schemaLocation="http://www.smallmind.org/schema/nutsnbolts/command http://www.smallmind.org/schema/nutsnbolts/smallmind-command-1.0.xsd">
  <option name="os" flag="o">
    <arguments>
      <single>operating system</single>
    </arguments>
  </option>
  <option name="app-user" flag="u" required="true">
    <arguments>
      <single>application user</single>
    </arguments>
  </option>
  <option name="install-dir" flag="i" required="true">
    <arguments>
      <single>installation directory</single>
    </arguments>
  </option>
  <option name="progress-bar" flag="b">
    <arguments>
      <single>emulate a graphical progress bar</single>
    </arguments>
  </option>
  <option name="nexus-host" flag="h" required="true">
    <arguments>
      <single>nexus host</single>
    </arguments>
  </option>
  <option name="nexus-user" flag="n" required="true">
    <arguments>
      <single>nexus user</single>
    </arguments>
  </option>
  <option name="nexus-password" flag="p" required="true">
    <arguments>
      <single>nexus password</single>
    </arguments>
  </option>
  <option name="repository" flag="r">
    <arguments>
      <single>repository typeHint</single>
    </arguments>
  </option>
  <option name="group-id" flag="g" required="true">
    <arguments>
      <single>groupId</single>
    </arguments>
  </option>
  <option name="artifact-id" flag="a" required="true">
    <arguments>
      <single>artifactId</single>
    </arguments>
  </option>
  <option name="version" flag="v" required="true">
    <arguments>
      <single>version</single>
    </arguments>
  </option>
  <option name="classifier" flag="c">
    <arguments>
      <single>classifier</single>
    </arguments>
  </option>
  <option name="extension" flag="e">
    <arguments>
      <single>artifact extension</single>
    </arguments>
  </option>
  <option name="env" flag="x">
    <arguments>
      <list>env vars</list>
    </arguments>
  </option>
  <option name="decorators" flag="d">
    <arguments>
      <list>decorator classes</list>
    </arguments>
  </option>
</options>
